### ISSUE TITLE
`brew install` fails due to non-writable root dirs

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#151]
When using [sudo -u admin brew install](https://github.com/galaxyproject/starforge/blob/6c4f85eb8ef9784e214f1be44a0840976c0590f8/starforge/forge/wheels.py#L192) as root, `$HOME` remains `~root`, causing failures due to a non-writable home directory:

```
Error: Permission denied - /var/root/Library
Warning: Bottle installation failed: building from source.
Error: Permission denied - /var/root/Library
Traceback (most recent call last):
  File "/python/wheelenv/bin/starforge", line 9, in <module>
    load_entry_point('starforge==0.3', 'console_scripts', 'starforge')()
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/python/wheelenv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/python/wheelenv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/python/wheelenv/lib/python2.7/site-packages/starforge/commands/cmd_bdist_wheel.py", line 67, in cli
    forge.bdist_wheel(output=output, uid=uid, gid=gid)
  File "/python/wheelenv/lib/python2.7/site-packages/starforge/forge/wheels.py", line 193, in bdist_wheel
    'brew', 'install'] + pkgs, cwd='/tmp')
  File "/python/wheelenv/lib/python2.7/site-packages/starforge/forge/wheels.py", line 103, in execute
    run(cmd, cwd=cwd)
  File "/python/wheelenv/lib/python2.7/site-packages/starforge/execution/local.py", line 28, in run
    check_call(cmd, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', '-u', 'admin', 'brew', 'install', 'xz']' returned non-zero exit status 1
```

The fix needs to be applied to the starforge inside the image.

**Comment by natefoo** [comment]
Jenkins' macOS image has been updated to Starforge 0.3.1.
