### ISSUE TITLE
btrfs subvol delete needs to wait for QEMU shutdown

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#39]
Otherwise you can get:

``` console
Running: ssh root@fauxsx -- shutdown -h now
Shutdown NOW!

System shutdown time has arrived
Deleting snapshot: btrfs subvolume delete /home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de
Transaction commit: none (default)
Delete subvolume '/home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de'
ERROR: cannot delete '/home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de' - Device or resource busy
Traceback (most recent call last):
  File "./wheel.py", line 328, in <module>
    main()
  File "./wheel.py", line 324, in main
    osx_qemu(args)
  File "./wheel.py", line 238, in osx_qemu
    subprocess.check_call(delete_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['btrfs', 'subvolume', 'delete', '/home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de']' returned non-zero exit status 1
```

Wait a few more seconds and it's fine:

``` console
(starforge)nate@mjolnir0% btrfs subvolume delete /home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de
Transaction commit: none (default)
Delete subvolume '/home/nate/snapshots/@75a0e152-8337-11e5-9891-002436f4a7de'
```

**Comment by natefoo** [comment]
Fixed in ff927c7266aeb83df09cdf90efb2b1a312380fa2
