### ISSUE TITLE
--no-docker error messsage

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/starforge#53]
Probably a user error, but should this be a better error message?

```
% starforge wheel --no-docker --wheels-config=wheels/build/wheels.yml dictobj
Traceback (most recent call last):
  File "/home/john/workspace/starforge/.venv/bin/starforge", line 9, in <module>
    load_entry_point('starforge==0.0.1.dev0', 'console_scripts', 'starforge')()
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/john/workspace/starforge/.venv/lib/python2.7/site-packages/starforge-0.0.1.dev0-py2.7.egg/starforge/commands/cmd_wheel.py", line 108, in cli
    for name in forge.get_sdist_expected_names():
UnboundLocalError: local variable 'forge' referenced before assignment
```

**Comment by natefoo** [comment]
Not user error, just my questionable code.
