### ISSUE TITLE
Jenkins build reports success when actually failed.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/starforge#98]
Looking at build [90](https://jenkins.galaxyproject.org/job/starforge-wheels/90/console)

```
Detecting changes to wheels.yml...
Traceback (most recent call last):
  File "/home/jenkins/sfvenv/bin/starforge", line 11, in <module>
    sys.exit(starforge())
  <SNIP>
  File "/home/jenkins/sfvenv/local/lib/python2.7/site-packages/starforge/config/wheels.py", line 55, in open
    return cls(global_config, config_file=config_file)
  File "/home/jenkins/sfvenv/local/lib/python2.7/site-packages/starforge/config/wheels.py", line 62, in __init__
    self.load_config()
  File "/home/jenkins/sfvenv/local/lib/python2.7/site-packages/starforge/config/wheels.py", line 75, in load_config
    purepy=False)
  File "/home/jenkins/sfvenv/local/lib/python2.7/site-packages/starforge/config/wheels.py", line 36, in __init__
    self.imageset = imagesets[config.get('imageset', default_imageset)]
KeyError: 'default_plus_libpython-wheel'
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of b15a158cfe9dc68600b011a1109f7136da516c08 to SUCCESS with url https://jenkins.galaxyproject.org/job/starforge-wheels/90/ and message: 'Build finished. '
Using context: wheel-build
Finished: SUCCESS
```

we can see an obvious failure. wheels/build/jenkins.sh probably needs a set -ex

**Comment by hexylena** [comment]
Okay, has a `set -e`. I wonder why jenkins isn't calling that a crash.
